# constants.py

# Game constants
CELL_SIZE = 40
GAP_SIZE = 4
DEFAULT_BOARD_SIZE = 9
MIN_BOARD_SIZE = 5
MAX_BOARD_SIZE = 12
PADDING = 20

# Colors
BOARD_COLOR = "#F9F9F9"
LINE_COLOR = "#000000"
PLAYER1_COLOR = "blue"
PLAYER2_COLOR = "red"
PLAYER3_COLOR = "green"
PLAYER4_COLOR = "purple"
HIGHLIGHT_COLOR = "yellow"
WALL_PREVIEW_COLOR = "orange"
WALL_COLOR = "black"
BUTTON_BG = "#CCCCCC"
INITIAL_POSITION_COLOR = "gray"
START_SCREEN_BG = "#F0F0F0"